# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('http_method', models.CharField(db_index=True, max_length=10)),
                ('endpoint_category', models.CharField(choices=[('authentication', 'Authentication'), ('jobs', 'Jobs'), ('profile', 'Profile'), ('search', 'Search'), ('messaging', 'Messaging'), ('media', 'Media'), ('analytics', 'Analytics'), ('other', 'Other')], db_index=True, max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(db_index=True, help_text='Response time in milliseconds')),
                ('db_query_time_ms', models.PositiveIntegerField(blank=True, help_text='Database query time in milliseconds', null=True)),
                ('db_query_count', models.PositiveIntegerField(default=0)),
                ('cache_hit', models.BooleanField(blank=True, db_index=True, null=True)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('response_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('server_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('has_error', models.BooleanField(db_index=True, default=False)),
                ('error_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'response_times',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='response_ti_endpoin_70ba55_idx'), models.Index(fields=['endpoint_category', '-timestamp'], name='response_ti_endpoin_16442b_idx'), models.Index(fields=['http_method', 'status_code'], name='response_ti_http_me_7565bd_idx'), models.Index(fields=['-response_time_ms'], name='response_ti_respons_047a2f_idx'), models.Index(fields=['has_error', '-timestamp'], name='response_ti_has_err_cbb5ad_idx'), models.Index(fields=['user', '-timestamp'], name='response_ti_user_id_89378c_idx'), models.Index(fields=['cache_hit', 'response_time_ms'], name='response_ti_cache_h_3f035e_idx')],
            },
        ),
    ]
