# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_application', 'Job Application'), ('application_status', 'Application Status'), ('message', 'New Message'), ('job_posting', 'Job Posting'), ('interview', 'Interview'), ('system', 'System'), ('profile', 'Profile'), ('payment', 'Payment')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('related_object_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx'), models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_95c9c5_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_1106fe_idx'), models.Index(fields=['expires_at', 'is_read'], name='notificatio_expires_c06a05_idx')],
            },
        ),
    ]
