# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('latitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'regions',
                'indexes': [models.Index(fields=['country', 'state_province'], name='regions_country_a2b966_idx'), models.Index(fields=['is_active'], name='regions_is_acti_dadff5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('location_type', models.CharField(choices=[('job', 'Job Location'), ('user', 'User Location'), ('company', 'Company Location'), ('event', 'Event Location')], db_index=True, max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_remote_friendly', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='map.region')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=200)),
                ('search_context', models.CharField(choices=[('job_search', 'Job Search'), ('profile_update', 'Profile Update'), ('location_browse', 'Location Browse')], db_index=True, max_length=50)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='map.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_history',
                'indexes': [models.Index(fields=['user', '-searched_at'], name='location_hi_user_id_4d7fe1_idx'), models.Index(fields=['location', '-searched_at'], name='location_hi_locatio_b46e75_idx'), models.Index(fields=['search_context', '-searched_at'], name='location_hi_search__75a63e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city', 'state_province', 'country'], name='locations_city_40dabc_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_latitud_4052bd_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type', 'is_verified'], name='locations_locatio_aea85c_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['region', 'location_type'], name='locations_region__7e8252_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['created_at'], name='locations_created_146821_idx'),
        ),
    ]
