# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('active_applications', models.PositiveIntegerField(default=0)),
                ('jobs_posted', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('pending_applications', models.PositiveIntegerField(default=0)),
                ('reviewed_applications', models.PositiveIntegerField(default=0)),
                ('interview_applications', models.PositiveIntegerField(default=0)),
                ('accepted_applications', models.PositiveIntegerField(default=0)),
                ('rejected_applications', models.PositiveIntegerField(default=0)),
                ('active_job_posts', models.PositiveIntegerField(default=0)),
                ('total_job_applications_received', models.PositiveIntegerField(default=0)),
                ('jobs_filled', models.PositiveIntegerField(default=0)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, help_text="User's dashboard layout preferences")),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text="User's notification preferences")),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('stats_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dashboards',
            },
        ),
    ]
