# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(db_index=True, max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('resume', 'Resume'), ('portfolio', 'Portfolio'), ('avatar', 'Avatar'), ('company_logo', 'Company Logo'), ('attachment', 'Attachment'), ('other', 'Other')], db_index=True, max_length=20)),
                ('file_size', models.PositiveIntegerField(db_index=True, help_text='File size in bytes')),
                ('mime_type', models.CharField(db_index=True, max_length=100)),
                ('file_extension', models.CharField(db_index=True, max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('is_temporary', models.BooleanField(db_index=True, default=False)),
                ('access_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_accessed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='media.mediafolder')),
            ],
            options={
                'db_table': 'media_folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediafile')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediafolder')),
            ],
            options={
                'db_table': 'media_file_folders',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('download_source', models.CharField(blank=True, choices=[('direct', 'Direct Link'), ('profile', 'Profile Page'), ('job_application', 'Job Application'), ('message', 'Message Attachment'), ('api', 'API')], db_index=True, max_length=50)),
                ('was_successful', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='media.mediafile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'download_logs',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['owner', 'is_public'], name='media_folde_owner_i_12bc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['parent', 'name'], name='media_folde_parent__1c6f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafolder',
            unique_together={('owner', 'slug', 'parent')},
        ),
        migrations.AddIndex(
            model_name='mediafilefolder',
            index=models.Index(fields=['folder', '-added_at'], name='media_file__folder__3c9ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafilefolder',
            index=models.Index(fields=['file', '-added_at'], name='media_file__file_id_1c0385_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafilefolder',
            unique_together={('file', 'folder')},
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='media_files_uploade_b38433_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'is_public'], name='media_files_file_ty_f1c853_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='media_files_related_e32db9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['is_temporary', 'expires_at'], name='media_files_is_temp_3a78d3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['mime_type', 'file_size'], name='media_files_mime_ty_7e28fe_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['checksum'], name='media_files_checksu_a79073_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['file', '-downloaded_at'], name='download_lo_file_id_065d98_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['user', '-downloaded_at'], name='download_lo_user_id_fe915b_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['ip_address', '-downloaded_at'], name='download_lo_ip_addr_270012_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['download_source', '-downloaded_at'], name='download_lo_downloa_dbcc03_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['was_successful'], name='download_lo_was_suc_46f0a8_idx'),
        ),
    ]
