# Generated by Django 4.2.7 on 2025-07-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='search.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=200)),
                ('suggestion_type', models.CharField(choices=[('query', 'Query Suggestion'), ('category', 'Category'), ('location', 'Location'), ('company', 'Company'), ('skill', 'Skill')], db_index=True, max_length=20)),
                ('weight', models.PositiveIntegerField(db_index=True, default=0)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.location')),
            ],
            options={
                'db_table': 'search_suggestions',
                'ordering': ['-weight', '-usage_count'],
                'indexes': [models.Index(fields=['text', 'suggestion_type'], name='search_sugg_text_88cc6c_idx'), models.Index(fields=['suggestion_type', 'is_active', '-weight'], name='search_sugg_suggest_2fb557_idx'), models.Index(fields=['category', '-weight'], name='search_sugg_categor_497341_idx'), models.Index(fields=['location', '-weight'], name='search_sugg_locatio_1ccabf_idx'), models.Index(fields=['is_featured', '-weight'], name='search_sugg_is_feat_930097_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=500)),
                ('normalized_query', models.CharField(db_index=True, max_length=500)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('search_type', models.CharField(choices=[('job_search', 'Job Search'), ('location_search', 'Location Search'), ('company_search', 'Company Search'), ('skill_search', 'Skill Search'), ('category_search', 'Category Search')], db_index=True, max_length=30)),
                ('job_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('experience_level', models.CharField(blank=True, db_index=True, max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('results_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('has_results', models.BooleanField(db_index=True, default=True)),
                ('clicked_result_position', models.PositiveIntegerField(blank=True, null=True)),
                ('clicked_result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['query_text', '-searched_at'], name='search_quer_query_t_1db240_idx'), models.Index(fields=['normalized_query', '-searched_at'], name='search_quer_normali_374ef5_idx'), models.Index(fields=['user', '-searched_at'], name='search_quer_user_id_bc0dc1_idx'), models.Index(fields=['search_type', '-searched_at'], name='search_quer_search__10b72b_idx'), models.Index(fields=['category', '-searched_at'], name='search_quer_categor_dc5679_idx'), models.Index(fields=['location', '-searched_at'], name='search_quer_locatio_c6e163_idx'), models.Index(fields=['has_results', 'results_count'], name='search_quer_has_res_3599de_idx'), models.Index(fields=['ip_address', '-searched_at'], name='search_quer_ip_addr_04d29d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query_text', models.CharField(blank=True, max_length=500)),
                ('job_type', models.CharField(blank=True, max_length=20)),
                ('experience_level', models.CharField(blank=True, max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('additional_filters', models.JSONField(blank=True, default=dict)),
                ('email_alerts', models.BooleanField(db_index=True, default=False)),
                ('alert_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('last_alert_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_searches',
                'ordering': ['-last_used', '-created_at'],
                'indexes': [models.Index(fields=['user', '-last_used'], name='saved_searc_user_id_97d5d1_idx'), models.Index(fields=['email_alerts', 'alert_frequency'], name='saved_searc_email_a_f9eeb5_idx'), models.Index(fields=['last_alert_sent'], name='saved_searc_last_al_603ef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=500, unique=True)),
                ('search_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('weekly_count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('is_suggested', models.BooleanField(db_index=True, default=True)),
                ('first_searched', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.category')),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.location')),
            ],
            options={
                'db_table': 'popular_searches',
                'ordering': ['-search_count'],
                'indexes': [models.Index(fields=['-search_count', 'is_suggested'], name='popular_sea_search__9fa4af_idx'), models.Index(fields=['-daily_count', 'is_trending'], name='popular_sea_daily_c_2c93ce_idx'), models.Index(fields=['-weekly_count'], name='popular_sea_weekly__5c2e67_idx'), models.Index(fields=['primary_category', '-search_count'], name='popular_sea_primary_fd1779_idx'), models.Index(fields=['primary_location', '-search_count'], name='popular_sea_primary_414c66_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='categories_parent__c20446_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'order'], name='categories_level_611955_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'job_count'], name='categories_is_acti_a6520e_idx'),
        ),
    ]
